# Generated by Django 4.0.5 on 2022-06-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='user_uploads', verbose_name='Profile Picture'),
        ),
    ]
